### PR TITLE
Fix #10 

### LINKED ISSUE #10: Change the definition of mention
On #8 we found that the current definition of mention might not be the best one.

I'm opening this issue to discuss which one is the best definition of mention, so we can implement it in the library!

Some things we found on #8:

`@Twinx@` -> Not a mention
`@ Texie` -> Not a mention
`Texie@sabertooth89` -> No mention here

And a question: should we allow punctuations marks or some symbols before the @ and after the username?

### PR DESCRIPTION
**Pull request by alorma**
Trying to implement #10 

- [x] Add tests proposed by @EsteveAguilera 
- [ ] Update definitions of mention

### CODE REVIEW

**Comment by EsteveAguilera** [comment]
Hi @alorma! Do you think you'll be able to move on with this draft?

**Comment by EsteveAguilera** [comment]
Oh @alorma, I was just asking! 

The tests you added are a great beginning... Will you reopen this PR if I create a new branch on the project where we/you/someone else can move on with this fix?

**Comment by alorma** [comment]
I don't have much time to work on this now, but i will support (even coding) if not alone :$

**Comment by EsteveAguilera** [comment]
Great @alorma !!!

I've just created a new branch [change-definition-of-mention](https://github.com/Fewlaps/mention-detector/tree/change-definition-of-mention)

You can reopen this PR pointing to that new branch so we can accept it and get that great tests!

**Pull request closed without merging**
